name: Opencart test

on:
  workflow_dispatch:
    inputs:
      branch: 
        default: 'main'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      HEADLESS: true

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Setup NodeJS
        uses: actions/setup-node@v3
      
      - name: Install dependencies
        run: npm i
      
      - name: Run tests
        run: npx codeceptjs run --reporter mochawesome

      - name: Publish test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: output
